---
- name: JCAT Install
  hosts: all
  gather_facts: yes
  vars:
    eclipse_home:         /JCAT
    atlas_client_version: "UC19W08"
    atlas_client_home:    "/atlas_client"
  tasks:

# Java

    - name: Install Java
      zypper:
        name: java
        state: present

# Git

    - name: Install Git
      zypper:
        name: git
        state: present

# GTK 3

    - name: Install Lib GTK 3
      zypper:
        name: libgtk-3-0
        state: present

# Eclipse Installation

    - file:
        path: "{{ eclipse_home }}"
        state: directory
        mode: 0777

    - name: Download and unarchive Eclipse files
      unarchive:
        src: "https://arm.rnd.ki.sw.ericsson.se/artifactory/proj-e3tools-external-local/4g/binaries/eclipse/eclipse-jee-neon-R-linux-gtk-x86_64.tar.gz"
        dest: "{{ eclipse_home }}"
        extra_opts: [--strip-components=1]
        remote_src: yes

    - name: Create eclipse symbolic link in /sbin
      file:
        src: "{{ eclipse_home }}/eclipse"
        dest: "/sbin/eclipse"
        mode: 0777
        state: link

# Atlas Client Installation

    - file:
        path: "{{ atlas_client_home }}"
        state: directory
        mode: 0777

    - name: Download Atlas Client
      get_url:
        url: "https://arm.rnd.ki.sw.ericsson.se/artifactory/simple/proj-jcat-release-local/hr/ericsson/jcat/univ/atlas/Atlas-client/{{ atlas_client_version }}/Atlas-client-{{ atlas_client_version }}.jar"
        dest: "{{ atlas_client_home }}/Atlas-client-{{ atlas_client_version }}.jar"