---

  # Task list: delete_vapp.yml
  # - Depends on:
  #   - query_specific_vapp_result
  #
  # - Provides: none
  #
  # - Description:
  #   Set of tasks necessary to delete vApp from vCloud.
  #

  - name: Delete vApp
    uri:
      url: "{{ query_specific_vapp_result.value }}"
      headers:
        Accept: "application/*+xml;version=30.0"
        x-vcloud-authorization:  "{{ vmware_login.x_vcloud_authorization }}"
        x-vcloud-token-type:  "{{ vmware_login.x_vmware_vcloud_token_type }}"
      method: DELETE
      return_content: yes
      dest: "{{ tmp_dir }}/delete_vapp.xml"
      status_code: 202
    register: delete_vapp

  - debug:
      var: delete_vapp.content
      verbosity: 3

  - name: Extract delete task href
    xml_read:
      xmlfile: "{{ tmp_dir }}/delete_vapp.xml"
      xpath: "/n:Task/@href"
      namespaces: "n=http://www.vmware.com/vcloud/v1.5"
    register: delete_vapp_task
    failed_when: delete_vapp_task.value == ""

  - debug:
      var: delete_vapp_task.value
      verbosity: 3

  - name: Wait until vApp is deleted
    uri:
      url: "{{ delete_vapp_task.value }}"
      headers:
        Accept: "application/*+xml;version=30.0"
        x-vcloud-authorization:  "{{ vmware_login.x_vcloud_authorization }}"
        x-vcloud-token-type:  "{{ vmware_login.x_vmware_vcloud_token_type }}"
        method: GET
      return_content: yes
    register: delete_vapp_task_result
    until: delete_vapp_task_result.content.find("status=\"success\"") != -1
    retries: "{{ vdc_retries }}"
    delay: "{{ vdc_delay }}"
