---
  # Task list: powerOn_vApp.yml
  # - Depends on:
  #   - query_specific_vapp_result
  #
  # - Provides:
  #   - none
  #
  # - Description:
  #   Set of tasks to power on vApp
  #

  - import_tasks: query_specific_vapp.yml
  - assert: { that: query_specific_vapp_result.value != "" }

  - name: Power ON vApp
    uri:
      url: "{{ query_specific_vapp_result.value }}/power/action/powerOn"
      headers:
        Accept: "application/*+xml;version=30.0"
        x-vcloud-authorization:  "{{ vmware_login.x_vcloud_authorization }}"
        x-vcloud-token-type:  "{{ vmware_login.x_vmware_vcloud_token_type }}"
      method: POST
      return_content: yes
      dest: "{{ tmp_dir }}/powerOn_vApp.xml"
      status_code: 202
      register: powerOn_vApp

  - debug:
      var: powerOn_vApp.content
      verbosity: 3

  - name: Extract vApp powerOn task href
    xml_read:
      xmlfile: "{{ tmp_dir }}/powerOn_vApp.xml"
      xpath: "/n:Task/@href"
      namespaces: "n=http://www.vmware.com/vcloud/v1.5"
    register: powerOn_vApp_task

  - debug:
      var: powerOn_vApp_task.value
      verbosity: 3

  - name: Wait until vApp is powered ON
    uri:
      url: "{{ powerOn_vApp_task.value }}"
      headers:
        Accept: "application/*+xml;version=30.0"
        x-vcloud-authorization:  "{{ vmware_login.x_vcloud_authorization }}"
        x-vcloud-token-type:  "{{ vmware_login.x_vmware_vcloud_token_type }}"
      method: GET
      return_content: yes
    register: powerOn_vApp_task_result
    until: powerOn_vApp_task_result.content.find("status=\"success\"") != -1
    retries: "{{ vdc_retries }}"
    delay: "{{ vdc_delay }}"

