---
  # Task list: query_specific_orgvdc.yml
  # - Depends on:
  #   - vdc_name
  #   - extra_filter_parameters
  #
  # - Provides:
  #   - query_specific_orgvdc_result
  #
  # - Description:
  #   Set of tasks to query VMware API for specific Org VDC ().
  #   Customizable filter options, can be tailored for specific use.
  #

  - name: VMware vCloud API query - Org VDC
    uri:
      url: "{{ api_host_vmware }}/api/query?type=orgVdc&filter=(name=={{ vdc_name | urlencode }}{{ extra_filter_parameters | default('') }})"
      headers:
        Accept: "application/*+xml;version=33.0"
        x-vcloud-authorization:  "{{ vmware_login.x_vcloud_authorization }}"
        x-vcloud-token-type:  "{{ vmware_login.x_vmware_vcloud_token_type }}"
      method: GET
      return_content: yes
      dest: "{{ tmp_dir }}/query_specific_orgvdc.xml"
      status_code: 200
    register: query_specific_orgvdc

  - debug:
      var: query_specific_orgvdc.content
      verbosity: 3

  - name: Extract Org VDC href
    xml_read:
      xmlfile: "{{ tmp_dir }}/query_specific_orgvdc.xml"
      xpath: "/n:QueryResultRecords/n:OrgVdcRecord/@href"
      namespaces: "n=http://www.vmware.com/vcloud/v1.5"
    register: query_specific_orgvdc_result

  - debug:
      var: query_specific_orgvdc_result.value
      verbosity: 3

