---
  # Task list: update_vm_ip_address.yml
  # - Depends on:
  #   - vm_href
  #   - vm_ip_address
  #   - org_network_name
  #
  # - Provides: none
  #
  # - Description:
  #   Set of tasks to update VM IP address and track progress.
  #

  - name: Ready template
    template:
      src: "{{ playbook_dir }}/xml/networkConnectionSection.xml"
      dest: "{{ tmp_dir }}/networkConnectionSection.xml"

  - name: Update VM IP address
    uri:
      url: "{{ vm_href.value }}/networkConnectionSection/"
      body: "{{ lookup('template', tmp_dir + '/networkConnectionSection.xml') }}"
      headers:
        Accept: "application/*+xml;version=30.0"
        x-vcloud-authorization:  "{{ vmware_login.x_vcloud_authorization }}"
        x-vcloud-token-type:  "{{ vmware_login.x_vmware_vcloud_token_type }}"
        Content-Type: "application/vnd.vmware.vcloud.networkConnectionSection+xml"
      method: PUT
      return_content: yes
      status_code: 202
      dest: "{{ tmp_dir }}/update_vm_ip_address_task.xml"
    register: update_vm_ip_address

  - debug:
      var: update_vm_ip_address.content
      verbosity: 3

  - name: Extract VM IP update task href
    xml_read:
      xmlfile: "{{ tmp_dir }}/update_vm_ip_address_task.xml"
      xpath: "/n:Task/@href"
      namespaces: "n=http://www.vmware.com/vcloud/v1.5"
    register: update_vm_ip_address_task
    failed_when: update_vm_ip_address_task.value == ""

  - debug:
      var: update_vm_ip_address_task.value
      verbosity: 3

  - name: Wait until VM IP update task is complete
    uri:
      url: "{{ update_vm_ip_address_task.value }}"
      headers:
        Accept: "application/*+xml;version=30.0"
        x-vcloud-authorization:  "{{ vmware_login.x_vcloud_authorization }}"
        x-vcloud-token-type:  "{{ vmware_login.x_vmware_vcloud_token_type }}"
      method: GET
      return_content: yes
    register: update_vm_ip_address_task_result
    until: update_vm_ip_address_task_result.content.find("status=\"success\"") != -1
    retries: "{{ vdc_retries }}"
    delay: "{{ vdc_delay }}"

